condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/linear_gamma0_0_beamfull_sepguess_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/linear_gamma0_0_beamfull_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/linear_gamma0_1_beamfull_sepguess_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/linear_gamma0_1_beamfull_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/linear_gamma0_9_beamfull_sepguess_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/linear_gamma0_9_beamfull_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/linear_gamma1_0_beamfull_sepguess_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/linear_gamma1_0_beamfull_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/mlp_gamma0_0_beamfull_sepguess_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/mlp_gamma0_0_beamfull_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/mlp_gamma0_1_beam10_sepguess_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/mlp_gamma0_1_beamfull_sepguess_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/mlp_gamma0_1_beamfull_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/mlp_gamma0_9_beam10_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/mlp_gamma0_9_beamfull_sepguess_ontopic_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/mlp_gamma0_9_beamfull_sepguess_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/mlp_gamma0_9_beamfull_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/mlp_gamma1_0_beamfull_sepguess_train.sh
condor_submit /scratch/cluster/aish/rl_for_oal/condor/scripts/mlp_gamma1_0_beamfull_train.sh
